checkout/frames-android

android-sdk/build.gradle
android-sdk/src/main/java/com/checkout/android_sdk/Architecture/UseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/Input/CardInput.java
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CardFocusUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CardInputUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/Utils/AfterTextChangedListener.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CardFocusUseCaseTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CardInputUseCaseTest.kt
app/src/androidTest/java/checkout/checkout_android/BillingDetails_Test.java
app/src/androidTest/java/checkout/checkout_android/CardDetails_Test.java
app/src/androidTest/java/checkout/checkout_android/Flow_Test.java

I want to move the repo towards an MVP / `Clean` architecture. The easiest first step is to extract UseCases from the CardInput class and to write some tests for them.

Card input use cases

---

android-sdk/src/main/java/com/checkout/android_sdk/Architecture/UseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/Presenter/CardInputPresenter.kt
android-sdk/src/main/java/com/checkout/android_sdk/Presenter/CvvInputPresenter.kt
android-sdk/src/main/java/com/checkout/android_sdk/Presenter/MonthInputPresenter.kt
android-sdk/src/main/java/com/checkout/android_sdk/Presenter/YearInputPresenter.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CardFocusUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CardInputUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CvvFocusChangedUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CvvInputUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/MonthSelectedUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/YearSelectedUseCase.kt
android-sdk/src/test/java/com/checkout/android_sdk/Presenter/CardInputPresenterTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/Presenter/CvvInputPresenterTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/Presenter/MonthInputPresenterTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/Presenter/YearInputPresenterTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CardFocusUseCaseTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CardInputUseCaseTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CvvFocusChangedUseCaseTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CvvInputUseCaseTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/MonthSelectedUseCaseTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/YearSelectedUseCaseTest.kt

The UseCases (so far) are synchronous; so it's easier to use generics to simplify their usage.

Make UseCases synchronous for simplicity.

---

sdk/src/main/java/com/checkout/sdk/cardinput/CardFocusUseCase.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInput.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInputPresenter.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInputUiState.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInputUseCase.kt
sdk/src/test/java/com/checkout/sdk/architecture/BasePresenterTest.kt
sdk/src/test/java/com/checkout/sdk/cardinput/CardFocusUseCaseTest.kt
sdk/src/test/java/com/checkout/sdk/cardinput/CardInputPresenterTest.kt
sdk/src/test/java/com/checkout/sdk/cardinput/CardInputUseCaseTest.kt

Separated out some nested classes in CardInput (now that the project is organised by feature).
Also passed UseCases as method arguments to Presenter to simplify testing; and pulled the BasePresenter tests into a specific test for that class.

Separate card input classes

---

sdk/src/main/java/com/checkout/sdk/cardinput/CardFocusUseCase.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInput.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInputPresenter.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInputUiState.kt
sdk/src/main/java/com/checkout/sdk/cardinput/CardInputUseCase.kt
sdk/src/main/java/com/checkout/sdk/monthinput/MonthInput.kt
sdk/src/main/java/com/checkout/sdk/monthinput/MonthInputPresenter.kt
sdk/src/main/java/com/checkout/sdk/monthinput/MonthInputUiState.kt
sdk/src/test/java/com/checkout/sdk/architecture/BasePresenterTest.kt
sdk/src/test/java/com/checkout/sdk/cardinput/CardFocusUseCaseTest.kt
sdk/src/test/java/com/checkout/sdk/cardinput/CardInputPresenterTest.kt
sdk/src/test/java/com/checkout/sdk/cardinput/CardInputUseCaseTest.kt
sdk/src/test/java/com/checkout/sdk/monthinput/MonthInputPresenterTest.kt
sdk/src/test/java/com/checkout/sdk/monthinput/MonthInputUiStateTest.kt
sdk/src/test/java/com/checkout/sdk/monthinput/MonthSelectedUseCaseTest.kt

Separate MonthInput classes (now that we have the project organised by feature).

Separate month input classes

---

sdk/src/main/java/com/checkout/sdk/cvvinput/CvvFocusChangedUseCase.kt
sdk/src/main/java/com/checkout/sdk/cvvinput/CvvInput.kt
sdk/src/main/java/com/checkout/sdk/cvvinput/CvvInputPresenter.kt
sdk/src/main/java/com/checkout/sdk/cvvinput/CvvInputState.kt
sdk/src/main/java/com/checkout/sdk/cvvinput/CvvInputUseCase.kt
sdk/src/main/java/com/checkout/sdk/yearinput/YearInput.kt
sdk/src/main/java/com/checkout/sdk/yearinput/YearInputPresenter.kt
sdk/src/main/java/com/checkout/sdk/yearinput/YearInputUiState.kt
sdk/src/main/java/com/checkout/sdk/yearinput/YearSelectedUseCase.kt
sdk/src/test/java/com/checkout/sdk/cvvinput/CvvInputPresenterTest.kt
sdk/src/test/java/com/checkout/sdk/yearinput/YearInputPresenterTest.kt
sdk/src/test/java/com/checkout/sdk/yearinput/YearInputUiStateTest.kt
sdk/src/test/java/com/checkout/sdk/yearinput/YearSelectedUseCaseTest.kt

Wanted to separate out the smaller classes from YearInputPresenter and CvvInputPresenter now that we have a feature based package organization.

Separate classes from presenters

---

sdk/src/main/java/com/checkout/sdk/core/RequestGenerator.kt

Fix bug where Year is incorrectly sent when we fill in a billing address.

Fix bug in requesting token with an address.

---

README.md
android-sdk/src/main/java/com/checkout/android_sdk/Models/BillingModel.kt
android-sdk/src/main/java/com/checkout/android_sdk/Models/PhoneModel.kt
android-sdk/src/main/java/com/checkout/android_sdk/PaymentForm.java
android-sdk/src/main/java/com/checkout/android_sdk/Request/CardTokenisationRequest.java
android-sdk/src/main/java/com/checkout/android_sdk/Response/CardTokenisationFail.java
android-sdk/src/main/java/com/checkout/android_sdk/Response/CardTokenisationResponse.java
android-sdk/src/main/java/com/checkout/android_sdk/Response/GooglePayTokenisationFail.java
android-sdk/src/main/java/com/checkout/android_sdk/Response/GooglePayTokenisationResponse.java
android-sdk/src/main/java/com/checkout/android_sdk/Store/DataStore.java
android-sdk/src/main/java/com/checkout/android_sdk/Utils/Environment.java
android-sdk/src/main/java/com/checkout/android_sdk/View/BillingDetailsView.java
android-sdk/src/main/java/com/checkout/android_sdk/View/CardDetailsView.java
android-sdk/src/test/java/com/checkout/android_sdk/DataStoreTests.java
app/src/main/java/checkout/checkout_android/DemoActivity.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

The tokenisation endpoint used in the  Unified Payments API  provides aditional information like (BIN, issuer details...). The endpoint and models used were updated to cater to the new format.
* [x ] New feature (non-breaking change which adds functionality)

Update to new API endpoint

---

android-sdk/src/main/java/com/checkout/android_sdk/PaymentForm.java
android-sdk/src/main/java/com/checkout/android_sdk/Utils/CustomAdapter.java
app/src/main/java/checkout/checkout_android/DemoActivity.java

Added null checks to prevent NullPointerException when clearForm is used before the PageAdapter populates the views
Closes issue #53

Added bug fix for CustomAdapter NullPointerException on clearForm

---

android-sdk/src/main/res/values-fr/strings.xml

Add french translations
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Add fr strings

---

android-sdk/src/main/java/com/checkout/android_sdk/Input/CardInput.kt
android-sdk/src/main/java/com/checkout/android_sdk/Presenter/CardInputPresenter.kt
android-sdk/src/main/java/com/checkout/android_sdk/Store/DataStore.java
android-sdk/src/main/java/com/checkout/android_sdk/UseCase/CardInputUseCase.kt
android-sdk/src/main/java/com/checkout/android_sdk/Utils/BackKeyEventHandler.kt
android-sdk/src/main/java/com/checkout/android_sdk/Utils/KeyboardUtils.kt
android-sdk/src/main/java/com/checkout/android_sdk/View/BillingDetailsView.java
android-sdk/src/main/java/com/checkout/android_sdk/View/CardDetailsView.java
android-sdk/src/main/res/values-fr/strings.xml
android-sdk/src/main/res/values-ro/strings.xml
android-sdk/src/main/res/values/strings.xml
android-sdk/src/test/java/com/checkout/android_sdk/UseCase/CardInputUseCaseTest.kt

- Fixed bug where card number formatting is lost after a config change
- Fixed bug where the last card number is being restored for each new payment
- Added missing translations to "Edit"

Bug fix and updates to CardDetailsView

---

android-sdk/src/main/java/com/checkout/android_sdk/Input/AddressOneInput.java
android-sdk/src/main/java/com/checkout/android_sdk/PaymentForm.java
android-sdk/src/main/java/com/checkout/android_sdk/Utils/KeyboardUtils.kt
android-sdk/src/main/java/com/checkout/android_sdk/View/BillingDetailsView.java

- PhoneDetails are ignored unless billing details are provided
- Back navigation did not reset modifications properly

PIMOB-604 Added fix for issues occurring when injectPhone is used

---

README.md
android-sdk/build.gradle

Change product version to 3.0.1

---

android-sdk/build.gradle
android-sdk/src/main/java/com/checkout/android_sdk/CheckoutAPIClient.java
android-sdk/src/main/java/com/checkout/android_sdk/FramesLogger.kt
android-sdk/src/main/java/com/checkout/android_sdk/PaymentForm.java
android-sdk/src/main/java/com/checkout/android_sdk/Utils/CustomAdapter.java
android-sdk/src/main/java/com/checkout/android_sdk/View/CardDetailsView.java
android-sdk/src/main/java/com/checkout/android_sdk/View/data/LoggingState.kt
android-sdk/src/main/java/com/checkout/android_sdk/logging/FramesLoggingEventType.kt
android-sdk/src/main/java/com/checkout/android_sdk/logging/LoggingEventAttribute.kt

- Changes to logging / analytics to record the publicKey and tokenId
- Introduction of a new logging event when the billing form UI is used
No new unit tests introduced as the changes are not functional features, but rather housekeeping tasks

PI-1158 update logging functionality

---

android-sdk/build.gradle
app/build.gradle
build.gradle
jitpack.yml
product-config.gradle

Changes are isolated to `build.gradle`  files.
These changes were required to fix build failures occurring on JitPack

Release 3.1.0 - Fix build issues on JitPack

---

android-sdk/src/main/res/values-de/strings.xml
android-sdk/src/main/res/values-es/strings.xml
android-sdk/src/main/res/values-it/strings.xml

More translations for forms
My app is available in these languages, so I just add translations here in sdk

Add more translations (es, it, de)

---

android-sdk/src/main/res/values-de/strings.xml
android-sdk/src/main/res/values-es/strings.xml
android-sdk/src/main/res/values-it/strings.xml

Amended translations
I have tested from for both language for updated strings (German and Spanish)

#feature_PI_1704_translation

---

android-sdk/src/main/java/com/checkout/android_sdk/FramesLogger.kt
android-sdk/src/main/java/com/checkout/android_sdk/PaymentForm.java
android-sdk/src/main/java/com/checkout/android_sdk/Utils/CheckoutTheme.kt
android-sdk/src/main/java/com/checkout/android_sdk/Utils/CheckoutThemeInterface.kt
android-sdk/src/main/java/com/checkout/android_sdk/logging/FramesLoggingEventDataProvider.kt
android-sdk/src/main/java/com/checkout/android_sdk/logging/PaymentFormLanguageEventAttribute.kt
android-sdk/src/main/java/com/checkout/android_sdk/threeds/ThreedsWebViewClient.kt
android-sdk/src/main/res/values/colors.xml
android-sdk/src/main/res/values/styles.xml
android-sdk/src/test/java/com/checkout/android_sdk/PaymentFormTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/logging/FramesLoggingEventsTest.kt
android-sdk/src/test/java/com/checkout/android_sdk/utils/CheckoutThemeTest.kt

1. Added log events for Checkout Theme value changed
2. Added Unit test to support log events' changes
1. Required to work out for sending font details like font name to events.
2. Just to update, Currently changing the status bar colour is not supported. Included all attributes for customization except font details. Additionally, sending extra details for textcolorPrimary, colorControlActivated to events if the merchant has added this …

PI-1706: Log when CheckoutTheme values are changed

---

checkout/src/main/java/com/checkout/base/model/CardScheme.kt
checkout/src/main/java/com/checkout/validation/error/ValidationError.kt
checkout/src/main/java/com/checkout/validation/validator/CvvValidator.kt
checkout/src/test/java/com/checkout/validation/validator/CvvValidatorTest.kt

[PIMOB-1285](https://checkout.atlassian.net/browse/PIMOB-1285)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

PIMOB-1285:  Eager cvv check

---

buildSrc/src/main/java/Dependencies.kt
buildSrc/src/main/java/Versions.kt
buildSrc/src/main/java/com/checkout/buildsrc/BaseDependencies.kt
buildSrc/src/main/java/com/checkout/buildsrc/CommonConfig.kt
buildSrc/src/main/java/com/checkout/buildsrc/utils/DependencyHandlerUtilExtensions.kt
checkout/src/main/java/com/checkout/CardValidatorFactory.kt
code_quality_tools/detekt.yml
example_app_frames/build.gradle.kts
frames/build.gradle.kts
frames/src/main/java/com/checkout/frames/component/cardnumber/CardNumberComponent.kt
frames/src/main/java/com/checkout/frames/component/cardnumber/CardNumberViewModel.kt
frames/src/main/java/com/checkout/frames/di/base/InjectionClient.kt
frames/src/main/java/com/checkout/frames/di/base/Injector.kt
frames/src/main/java/com/checkout/frames/di/component/CardNumberViewModelSubComponent.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/di/module/StylesModule.kt
frames/src/main/java/com/checkout/frames/di/module/ValidationModule.kt

[PIMOB-1385  Configure DI and create payment form component scaffold with DI](https://checkout.atlassian.net/browse/PIMOB-1385)
Dagger 2 was used as DI framework.

PIMOB-1385  Configure DI and create payment form component scaffold with DI

---

code_quality_tools/detekt.yml
frames/src/main/java/com/checkout/frames/component/cardnumber/CardNumberViewModel.kt
frames/src/main/java/com/checkout/frames/style/view/InputFieldViewStyle.kt
frames/src/main/java/com/checkout/frames/view/InputField.kt

[PIMOB-1398: Card number component. RTL.](https://checkout.atlassian.net/browse/PIMOB-1398)
Possibility to use LTR even for RTL layouts but with end alignment.

PIMOB-1398: Rtl improvement for card number component.

---

frames/src/test/java/com/checkout/frames/component/cardnumber/CardNumberTransformationTest.kt
frames/src/test/java/com/checkout/frames/component/cardnumber/CardNumberViewModelTest.kt

[PIMOB-1399: Card number component. Tests.](https://checkout.atlassian.net/browse/PIMOB-1399)
View model and visual transformation were covered with unit tests.

PIMOB-1399: Card number component. Unit tests.

---

frames/src/main/java/com/checkout/frames/component/expirydate/ExpiryDateComponentState.kt
frames/src/main/java/com/checkout/frames/component/expirydate/ExpiryDateViewModel.kt
frames/src/main/res/values/strings.xml

[PIMOB-1401](https://checkout.atlassian.net/browse/PIMOB-1401)
Error handling was implemented for expiry date.

PIMOB-1401: Error handling was added.

---

frames/src/main/java/com/checkout/frames/component/expirydate/ExpiryDateComponent.kt
frames/src/main/java/com/checkout/frames/component/expirydate/ExpiryDateViewModel.kt
frames/src/main/java/com/checkout/frames/di/module/StylesModule.kt
frames/src/test/java/com/checkout/frames/component/expirydate/ExpiryDateViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/expirydate/ExpiryDateVisualTransformationTest.kt
frames/src/test/java/com/checkout/frames/component/expirydate/SmartExpiryDateValidationUseCaseTest.kt

[PIMOB-1404](https://checkout.atlassian.net/browse/PIMOB-1404)
Test cases for expiry date component were added 

PIMOB-1404: Test cases for expiry date component.

---

frames/src/main/java/com/checkout/frames/component/country/CountryComponent.kt
frames/src/main/java/com/checkout/frames/component/country/CountryViewModel.kt
frames/src/main/java/com/checkout/frames/di/component/CountryViewModelSubComponent.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/di/module/PaymentModule.kt
frames/src/main/java/com/checkout/frames/di/module/StylesModule.kt
frames/src/main/java/com/checkout/frames/mapper/InputFieldStyleToInputFieldStateMapper.kt
frames/src/main/java/com/checkout/frames/mapper/InputFieldStyleToViewStyleMapper.kt
frames/src/main/java/com/checkout/frames/model/InputFieldColors.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt
frames/src/main/java/com/checkout/frames/style/component/CountryComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultCountryComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/PaymentDetailsStyle.kt
frames/src/main/java/com/checkout/frames/style/view/InputFieldViewStyle.kt
frames/src/main/java/com/checkout/frames/utils/extensions/InputFieldIndicatorStyleExtensions.kt
frames/src/main/java/com/checkout/frames/view/InputField.kt
frames/src/main/res/drawable/cko_ic_caret_right.xml

[PIMOB-1429: Country field component](https://checkout.atlassian.net/browse/PIMOB-1429)
Country field component was created.

PIMOB-1429: Country field component

---

frames/src/main/java/com/checkout/frames/component/country/CountryComponent.kt
frames/src/main/java/com/checkout/frames/component/country/CountryViewModel.kt
frames/src/main/java/com/checkout/frames/di/component/CountryViewModelSubComponent.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/di/module/PaymentModule.kt
frames/src/main/java/com/checkout/frames/di/module/StylesModule.kt
frames/src/main/java/com/checkout/frames/mapper/InputFieldStyleToInputFieldStateMapper.kt
frames/src/main/java/com/checkout/frames/mapper/InputFieldStyleToViewStyleMapper.kt
frames/src/main/java/com/checkout/frames/model/InputFieldColors.kt
frames/src/main/java/com/checkout/frames/screen/countrypicker/CountryPickerViewModel.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt
frames/src/main/java/com/checkout/frames/style/component/CountryComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultCountryComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/PaymentDetailsStyle.kt
frames/src/main/java/com/checkout/frames/style/view/InputFieldViewStyle.kt
frames/src/main/java/com/checkout/frames/utils/extensions/InputFieldIndicatorStyleExtensions.kt
frames/src/main/java/com/checkout/frames/view/InputField.kt
frames/src/main/res/drawable/cko_ic_caret_right.xml
frames/src/test/java/com/checkout/frames/component/country/CountryViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/cvv/CvvViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/countrypicker/CountryPickerViewModelTest.kt

[PIMOB-1430: Country picker screen and field component. Unit tests.](https://checkout.atlassian.net/browse/PIMOB-1430)
Unit tests.

PIMOB-1430: Country picker screen and field component. Unit tests.

---

checkout/src/main/java/com/checkout/tokenization/model/Address.kt
frames/src/main/java/com/checkout/frames/component/country/CountryViewModel.kt
frames/src/main/java/com/checkout/frames/screen/billingformdetails/BillingFormDetailsScreen.kt
frames/src/main/java/com/checkout/frames/screen/billingformdetails/models/BillingAddress.kt
frames/src/main/java/com/checkout/frames/screen/billingformdetails/models/BillingForm.kt
frames/src/main/java/com/checkout/frames/screen/countrypicker/CountryPickerViewModel.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt
frames/src/main/java/com/checkout/frames/screen/navigation/NavigationConstants.kt
frames/src/main/java/com/checkout/frames/screen/navigation/Screen.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormScreen.kt
frames/src/test/java/com/checkout/frames/component/country/CountryViewModelTest.kt
frames/src/test/java/com/checkout/frames/countrypicker/CountryPickerViewModelTest.kt

[PIMOB-1450](https://checkout.atlassian.net/browse/PIMOB-1450)
1. data and navigation objects were added.
It was created to synced up between the billing form page and its summary components.

PIMOB-1450 data objects for billing form page were added.

---

frames/src/main/java/com/checkout/frames/mapper/ButtonStyleToInternalStateMapper.kt
frames/src/main/java/com/checkout/frames/mapper/ButtonStyleToInternalViewStyleMapper.kt
frames/src/main/java/com/checkout/frames/model/BorderStroke.kt
frames/src/main/java/com/checkout/frames/model/ButtonElevation.kt
frames/src/main/java/com/checkout/frames/model/Margin.kt
frames/src/main/java/com/checkout/frames/model/Padding.kt
frames/src/main/java/com/checkout/frames/style/component/base/ButtonStyle.kt
frames/src/main/java/com/checkout/frames/style/view/InternalButtonViewStyle.kt
frames/src/main/java/com/checkout/frames/style/view/TextLabelViewStyle.kt
frames/src/main/java/com/checkout/frames/utils/extensions/PaddingExtensions.kt
frames/src/main/java/com/checkout/frames/view/InternalButton.kt
frames/src/main/java/com/checkout/frames/view/InternalButtonState.kt
frames/src/main/java/com/checkout/frames/view/TextLabel.kt

[PIMOB-1449: Billing form Summary: Create base button component](https://checkout.atlassian.net/browse/PIMOB-1449)
Base button component was created. It should be used for all buttons and be able to fulfill all current needs.
Samples of button design:
Sample of enabled and disabled state:
https://user-images.githubusercontent.com/105640154/194910528-d9e97b03-f89b-403e-92cf-141197d7821c.mov

PIMOB-1449: Billing form Summary: Create base button component

---

checkout/src/main/java/com/checkout/logging/EventLoggerProvider.kt
checkout/src/main/java/com/checkout/logging/Logger.kt
checkout/src/main/java/com/checkout/logging/LoggingEventType.kt
checkout/src/main/java/com/checkout/logging/model/LoggingEvent.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt
frames/src/main/java/com/checkout/frames/component/cardnumber/CardNumberComponent.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormConfig.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormScreen.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormViewModel.kt
frames/src/main/java/com/checkout/frames/tokenization/CardTokenizationUseCase.kt
frames/src/main/java/com/checkout/frames/tokenization/TokenizationResultHandler.kt
frames/src/main/java/com/checkout/frames/utils/constants/DINamedConstants.kt

[PIMOB-1469: Card tokenization with headless SDK.](https://checkout.atlassian.net/browse/PIMOB-1469)
- Business logic for tokenization was added. Headless SDK was used.
- Logger was added to the dependency graph.
- Card number component previews were removed.

PIMOB-1469: Card tokenization with headless SDK.

---

example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt
frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonComponent.kt
frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonViewModel.kt
frames/src/main/java/com/checkout/frames/component/provider/ComponentProvider.kt
frames/src/main/java/com/checkout/frames/component/provider/ComposableComponentProvider.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/component/PayButtonViewModelSubComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/di/module/StylesModule.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt
frames/src/main/java/com/checkout/frames/style/component/PayButtonComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultButtonStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultPayButtonComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultTextLabelStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/PaymentDetailsStyle.kt
frames/src/main/java/com/checkout/frames/style/view/InternalButtonViewStyle.kt
frames/src/main/java/com/checkout/frames/tokenization/CardTokenizationUseCase.kt
frames/src/main/java/com/checkout/frames/tokenization/InternalCardTokenRequest.kt
frames/src/main/java/com/checkout/frames/utils/constants/PaymentButtonConstants.kt
frames/src/main/java/com/checkout/frames/utils/extensions/StringExtensions.kt
frames/src/main/java/com/checkout/frames/view/InternalButtonState.kt
frames/src/main/res/values/strings.xml
frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt
frames/src/test/java/com/checkout/frames/tokenization/CardTokenizationUseCaseTest.kt
frames/src/test/java/com/checkout/frames/utils/extensions/StringExtensionsKtTest.kt

[PIMOB-1475: Create payment button component.](https://checkout.atlassian.net/browse/PIMOB-1475)
Pay button component was implemented and added on the Payment details screen.

PIMOB-1475: Payment button component

---

example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt
frames/src/main/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModel.kt
frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonViewModel.kt
frames/src/main/java/com/checkout/frames/di/NamedConstants.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/di/module/StylesModule.kt
frames/src/main/java/com/checkout/frames/mapper/ImageStyleToClickableComposableImageMapper.kt
frames/src/main/java/com/checkout/frames/model/request/ImageStyleToClickableImageRequest.kt
frames/src/main/java/com/checkout/frames/paymentflow/CardTokenizationUseCase.kt
frames/src/main/java/com/checkout/frames/paymentflow/ClosePaymentFlowUseCase.kt
frames/src/main/java/com/checkout/frames/paymentflow/InternalCardTokenRequest.kt
frames/src/main/java/com/checkout/frames/paymentflow/PaymentFlowHandler.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormConfig.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormScreen.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormViewModel.kt
frames/src/main/java/com/checkout/frames/style/component/ScreenHeaderStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultLightStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultPayButtonComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultTextLabelStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/PaymentDetailsStyle.kt
frames/src/main/java/com/checkout/frames/utils/constants/HeaderTitleConstants.kt
frames/src/main/java/com/checkout/frames/utils/constants/PaymentButtonConstants.kt
frames/src/main/res/values/strings.xml
frames/src/test/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt
frames/src/test/java/com/checkout/frames/tokenization/CardTokenizationUseCaseTest.kt

[PIMOB-1464: Create header for default UI page](https://checkout.atlassian.net/browse/PIMOB-1464)
Header for payment details screen was added.

PIMOB-1464: Create header for default UI page

---

frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt

[PIMOB-1436: Reset focus on background press for payment details screen.](https://checkout.atlassian.net/browse/PIMOB-1436)
Focus reset on background press for payment details screen was added.

PIMOB-1436: Reset focus on background press for payment details screen.

---

checkout/src/main/java/com/checkout/tokenization/model/Address.kt
frames/src/main/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModel.kt
frames/src/main/java/com/checkout/frames/component/billingaddressfields/BillingAddressDynamicInputComponent.kt
frames/src/main/java/com/checkout/frames/component/billingaddressfields/BillingAddressInputComponentState.kt
frames/src/main/java/com/checkout/frames/mapper/InputFieldStyleToViewStyleMapper.kt
frames/src/main/java/com/checkout/frames/mapper/billingaddressdetails/BillingAddressInputComponentStyleToStateMapper.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsScreen.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingAddress.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressform/BillingAddressFormScreen.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt
frames/src/main/java/com/checkout/frames/style/component/base/InputFieldStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultLightStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/default/DefaultBillingAddressDetailsStyle.kt
frames/src/main/java/com/checkout/frames/utils/constants/BillingAddressDetailsConstants.kt
frames/src/main/java/com/checkout/frames/utils/extensions/BillingAddressDetailsExtensions.kt
frames/src/main/java/com/checkout/frames/utils/extensions/BillingAddressExtensions.kt
frames/src/main/java/com/checkout/frames/utils/extensions/KeyboardExtensions.kt
frames/src/main/res/values/strings.xml
frames/src/test/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModelTest.kt

[PIMOB-1461](https://checkout.atlassian.net/browse/PIMOB-1461)
1 Error validation part for fields
2 Update address summary componenet
3 Update button state along with validation.

PIMOB-1461: Sync Save button with address fields.

---

frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/usecase/BillingAddressInputComponentStateUseCase.kt
frames/src/main/res/values/strings.xml
frames/src/test/java/com/checkout/frames/mock/BillingAddressDetailsTestData.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/usecase/BillingAddressInputComponentStateUseCaseTest.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/usecase/BillingAddressInputComponentStyleUseCaseTest.kt

[PIMOB-1462](https://checkout.atlassian.net/browse/PIMOB-1462)
Unit tests were implemented

PIMOB-1462 unit tests billing form

---

frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/usecase/BillingAddressInputComponentStateUseCase.kt
frames/src/main/res/values/strings.xml
frames/src/test/java/com/checkout/frames/mock/BillingAddressDetailsTestData.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/usecase/BillingAddressInputComponentStateUseCaseTest.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/usecase/BillingAddressInputComponentStyleUseCaseTest.kt

[PIMOB-1346](https://checkout.atlassian.net/browse/PIMOB-1346)
Billing address details was implemented 

PIMOB-1346: Create billing form page

---

frames/src/main/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModel.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/style/component/addresssummary/AddressSummaryComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultAddressSummaryComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultCardNumberComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultCvvComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultExpiryDateComponentStyle.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultLightStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/PaymentDetailsStyle.kt
frames/src/main/java/com/checkout/frames/style/screen/default/DefaultBillingAddressDetailsStyle.kt
frames/src/main/java/com/checkout/frames/utils/constants/PaymentButtonConstants.kt
frames/src/main/java/com/checkout/frames/utils/constants/PaymentDetailsScreenConstants.kt
frames/src/main/res/values/strings.xml
frames/src/test/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt
frames/src/test/java/com/checkout/frames/manager/PaymentFormStateManagerTest.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt

[PIMOB-1468: All components should have an isMandatory property](https://checkout.atlassian.net/browse/PIMOB-1468)
CVV and address summary components can be hidden, and related validation logic improved.
Address summary component can be optional and related validation logic improved.

PIMOB-1468: All components should have an isMandatory property

---

buildSrc/src/main/java/CheckoutConfig.kt
buildSrc/src/main/java/FramesConfig.kt
buildSrc/src/main/java/com/checkout/buildsrc/BuildConfigFieldName.kt
checkout/build.gradle.kts
checkout/src/main/java/com/checkout/logging/EventLogger.kt
checkout/src/main/java/com/checkout/logging/Logger.kt
example_app_frames/build.gradle.kts
frames/build.gradle.kts
frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonViewModel.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/logging/PaymentFormEventType.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/utils/extensions/LoggerExtensions.kt
frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt

[PIMOB-1502 Logging for Payment Form was updated.](https://checkout.atlassian.net/browse/PIMOB-1502)
Next log events were added:
- payment_form_initialised
- payment_form_presented
- payment_form_submitted
- payment_form_cancelled

PIMOB-1502 Logging for Payment Form was updated.

---

frames/src/main/java/com/checkout/frames/logging/BillingFormEventType.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/utils/extensions/LoggerExtensions.kt
frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt

[PIMOB-1503: Update logging for Billing Address](https://checkout.atlassian.net/browse/PIMOB-1503)
Event logging for the Billing form was implemented.

PIMOB-1502: Logging for Payment Form was updated.

---

checkout/src/main/java/com/checkout/tokenization/usecase/ValidateTokenizationDataUseCase.kt
checkout/src/test/java/com/checkout/validation/validator/usecase/ValidateTokenizationDataUseCaseTest.kt

[PIMOB-1500: Checkout Android should allow tokenisation without the CVV](https://checkout.atlassian.net/browse/PIMOB-1500)
Tokenisation can be done without a CVV.

PIMOB-1500: Allow tokenisation without CVV

---

checkout/src/main/java/com/checkout/base/model/CardScheme.kt
checkout/src/test/java/com/checkout/validation/validator/CardNumberValidatorTest.kt
frames/src/test/java/com/checkout/frames/component/cardnumber/CardNumberTransformationTest.kt

[PIMOB-1437: Unable to enter a 19-digit Visa card](https://checkout.atlassian.net/browse/PIMOB-1437)
19 digit Visa card number support was added.

PIMOB-1437: Unable to enter a 19-digit Visa card

---

app/src/main/java/checkout/checkout_android/DemoActivity.java
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt
frames/src/main/java/com/checkout/frames/api/PaymentFlowHandler.kt
frames/src/main/java/com/checkout/frames/component/cardnumber/CardNumberViewModel.kt
frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonViewModel.kt
frames/src/main/java/com/checkout/frames/di/component/FramesDIComponent.kt
frames/src/main/java/com/checkout/frames/di/injector/FramesInjector.kt
frames/src/main/java/com/checkout/frames/model/request/InternalCardTokenRequest.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormConfig.kt
frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormViewModel.kt
frames/src/main/java/com/checkout/frames/usecase/CardTokenizationUseCase.kt
frames/src/main/java/com/checkout/frames/usecase/ClosePaymentFlowUseCase.kt
frames/src/test/java/com/checkout/frames/component/cardnumber/CardNumberViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt
frames/src/test/java/com/checkout/frames/tokenization/CardTokenizationUseCaseTest.kt

[PIMOB-1455: Card number should throw an error when the card scheme input is not in the list of accepted schemes](https://checkout.atlassian.net/browse/PIMOB-1455)
Show error for unsupported card schemes

PIMOB-1455: Card number should throw an error when the card scheme input is not in the list of accepted schemes

---

example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentFormTheme.kt
frames/src/main/java/com/checkout/frames/mapper/theme/PaymentDetailsStyleMapper.kt
frames/src/main/java/com/checkout/frames/style/theme/PaymentFormThemeColors.kt

[PIMOB-1517: Improvement in theming (Add additional layer for colors for merchant)](https://checkout.atlassian.net/browse/PIMOB-1517)
Theming color creation approach improved

PIMOB-1517 Theming color creation approach improved

---

example_app_frames/src/main/java/com/checkout/example/frames/navigation/NavigationConstants.kt
example_app_frames/src/main/java/com/checkout/example/frames/navigation/Screen.kt
example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomBillingFormStyle.kt
example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentDetailsStyle.kt
example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/PaymentFormConstants.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/HomeScreen.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt
example_app_frames/src/main/res/drawable/ic_back_arrow.xml
example_app_frames/src/main/res/values/strings.xml

[PIMOB-1347](https://checkout.atlassian.net/browse/PIMOB-1347)
Custom version sample added in sample app.

PIMOB-1347: Create custom version

---

checkout/src/main/java/com/checkout/CardValidatorFactory.kt
checkout/src/main/java/com/checkout/CheckoutApiServiceFactory.kt
checkout/src/main/java/com/checkout/base/model/CardScheme.kt
checkout/src/main/java/com/checkout/base/model/Country.kt
example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomBillingFormStyle.kt
frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingFormFields.kt

[PIMOB-1530: Java compatibility issue with static functions](https://checkout.atlassian.net/browse/PIMOB-1530)
All public static functions were annotated with @JvmStatic.

PIMOB-1530: Java compatibility issue with static functions

---

buildSrc/src/main/java/Versions.kt
frames/src/main/java/com/checkout/frames/component/addresssummary/AddressSummaryComponent.kt
frames/src/main/java/com/checkout/frames/style/view/InputFieldViewStyle.kt
frames/src/main/java/com/checkout/frames/view/InputField.kt

[PIMOB-1532: Migrate to stable material 3 library version](https://checkout.atlassian.net/browse/PIMOB-1532)
Material 3 library was migrated to stable 1.0.1 version.

PIMOB-1532: Migrate to stable material 3 library version

---

checkout/src/main/java/com/checkout/tokenization/mapper/response/CardTokenizationNetworkDataMapper.kt
checkout/src/main/java/com/checkout/tokenization/model/TokenDetails.kt
checkout/src/main/java/com/checkout/tokenization/response/TokenDetailsResponse.kt
checkout/src/test/java/com/checkout/mock/CardTokenTestData.kt
checkout/src/test/java/com/checkout/tokenization/mapper/CardTokenizationNetworkDataMapperTest.kt
frames/src/test/java/com/checkout/frames/tokenization/CardTokenizationUseCaseTest.kt

[PIMOB-1533: Add local_scheme in tokenisation response](https://checkout.atlassian.net/browse/PIMOB-1533)
local_scheme was added in tokenisation response.

PIMOB-1533  Add local_scheme in tokenisation response

---

README.md

[PIMOB-1536: Add integration doc link to repo README](https://checkout.atlassian.net/browse/PIMOB-1536)
The integration doc link to the repo README was added.
https://www.checkout.com/docs/integrate/sdks/android-sdk

PIMOB-1536  Add integration doc link to repo README

---

.github/PULL_REQUEST_TEMPLATE.md

PIMOB-2101
Add a `Test Steps` section in the  PR Template
[PIMOB-2101]: https://checkout.atlassian.net/browse/PIMOB-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIMOB-2101: Add Test Steps in the PR template

---

frames/src/main/java/com/checkout/frames/component/cardholdername/CardHolderNameViewModel.kt
frames/src/main/java/com/checkout/frames/component/cardnumber/CardNumberViewModel.kt
frames/src/main/java/com/checkout/frames/component/cvv/CvvViewModel.kt
frames/src/main/java/com/checkout/frames/component/expirydate/ExpiryDateViewModel.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt
frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt
frames/src/test/java/com/checkout/frames/component/cardnumber/CardNumberViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/cvv/CvvViewModelTest.kt
frames/src/test/java/com/checkout/frames/component/expirydate/ExpiryDateViewModelTest.kt
frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt

[PIMOB-1631](https://checkout.atlassian.net/browse/PIMOB-1631)
- Problem statement: Currently, our requirement is when we change the focus, especially for card-sensitive fields if they are not valid then show the error and disable the pay button. However, this same logic needs to be updated user changing input of card-sensitive fields/mandatory fields, the pay button should be enabled/disabled and no errors should be visible except the card number component.
Changes: Added logic in oninputChange functions for all card sensitive components to enable/disable pay button and to not show errors on it while typing it
_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._ 
- Add data into all …

PIMOB-1631: improved validation for pay button

---

checkout/src/main/java/com/checkout/tokenization/mapper/response/CardTokenizationNetworkDataMapper.kt
checkout/src/main/java/com/checkout/tokenization/mapper/response/PhoneEntityToPhoneDataMapper.kt
checkout/src/test/java/com/checkout/tokenization/mapper/CardTokenizationNetworkDataMapperTest.kt
checkout/src/test/java/com/checkout/tokenization/mapper/response/PhoneEntityToPhoneDataMapperTest.kt
frames/src/main/java/com/checkout/frames/di/module/PaymentModule.kt
frames/src/main/java/com/checkout/frames/mapper/BillingFormAddressToBillingAddressMapper.kt
frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt
frames/src/main/java/com/checkout/frames/style/component/default/DefaultCardHolderNameComponentStyle.kt
frames/src/test/java/com/checkout/frames/mapper/BillingFormAddressToBillingAddressMapperTest.kt
frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt
frames/src/test/java/com/checkout/frames/style/DefaultCardHolderNameComponentStyleTest.kt

[PIMOB-2114](https://checkout.atlassian.net/browse/PIMOB-2114)
1. Fixed bug for enabling pay button while cardholder name is prefilled
2. Added unit tests
3. Addressing comments from previous pr
_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._ 
> For instance:
> 1. Go to the main screen
> 2. Tap on primary button
> 3. Verify the image is shown on the screen
_If this is a relatively large or complex change, kick off the discussion …

PIMOB:2114 - fixed pay button issue for cardholdername while prefilled

---

example_app_frames/src/main/java/com/checkout/example/frames/styling/CustomCVVInputFieldStyle.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/component/CustomButton.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/CVVTokenizationScreen.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/LoadCVVComponentsContents.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt
example_app_frames/src/main/java/com/checkout/example/frames/ui/viewmodel/CVVTokenizationViewModel.kt
example_app_frames/src/main/res/values/strings.xml
frames/src/main/java/com/checkout/frames/cvvinputfield/CVVInputField.kt
frames/src/main/java/com/checkout/frames/cvvinputfield/api/CVVComponentMediator.kt
frames/src/main/java/com/checkout/frames/cvvinputfield/api/InternalCVVComponentMediator.kt
frames/src/main/java/com/checkout/frames/cvvinputfield/models/CVVComponentConfig.kt
frames/src/main/java/com/checkout/frames/cvvinputfield/style/DefaultCVVInputFieldStyle.kt

[PIMOB-2182](https://checkout.atlassian.net/browse/PIMOB-2182)
1. Added default style for CVV component config
2. Added Custom and default CVV components for 2 different schemes visa and Maestro along with button for tokenisation
Changes in the SDK:
1. Improvement in CVVInputField, while recomposition from cvvcomponent config when user typing. viewmodel was creating everytime
2. improvement in InternalCVVComponentMediator, when user typing and the isEnteredCVV value changes then asynchronous recomposition result in an issue for the component  
Overall improvement: from the merchant app if it doing multiple time recomposing due to another components. SDK component will work as expected
_If there's any functionality change, please list a step by step guide of how to verify the changes, …

PIMOB:2182- kotlin sample app updated

---

jitpack.yml

[PIMOB-2214](https://checkout.atlassian.net/browse/PIMOB-2214)
Upgrading jdk version to 17 to fix jitpack build failure
Once it merged will trigger a build from Jitpack portal to test it
_If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered, etc..._
[PIMOB-2214]: https://checkout.atlassian.net/browse/PIMOB-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIMOB:2214: fix jitpack build issue by upgrading jdk version

---

.github/workflows/ui-test.yml
.github/workflows/verify-frames.yml

PIMOB-2627
Specify Mac OS image in GHA
Run UI test workflow and it should pass

PIMOB-2627: Fix UI Tests in GHA

---

example_app_frames/lint-baseline.xml
frames/lint-baseline.xml

no number
Updating lint-baseline file for release build to succeed

Updating lint-baseline

---

example_app_frames/lint-baseline.xml
frames/lint-baseline.xml

NO Issue number
Updating the lint baseline file

Updating lint

---

example_app_frames/lint-baseline.xml
frames/lint-baseline.xml

PIOMB-3507
Update lint baseline files

PIOMB-3507: Update lint baseline for 4.2.6
