checkout/frames-android

android-sdk/src/main/java/com/checkout/android_sdk/PaymentForm.java, android-sdk/src/main/java/com/checkout/android_sdk/Store/DataStore.java, android-sdk/src/main/java/com/checkout/android_sdk/View/BillingDetailsView.java
When `injectBilling` is called but `injectPhone` is not used a null pointer exception may occur. This change fixes these issues.
- NullPointerException if clearForm is also called
- NullPointerException if user navigates to Billing Details screen and presses the Back button or the toolbar navigation button
=> Fix issues with billing details

README.md, android-sdk/build.gradle, app/build.gradle
- Updated build version in preparation for the next release 3.1.0 (Marked -SNAPSHOT until formal release)
- Updated targetSdk to 31
- Updated README.md
=> Prepare for next version 3.1.0

android-sdk/src/main/java/com/checkout/android_sdk/Utils/CheckoutTheme.kt, android-sdk/src/main/java/com/checkout/android_sdk/logging/FramesLoggingEventDataProvider.kt, android-sdk/src/main/java/com/checkout/android_sdk/logging/PaymentFormLanguageEventAttribute.kt, android-sdk/src/test/java/com/checkout/android_sdk/logging/FramesLoggingEventsTest.kt
1 Shifted evenTheme properties to theme object
2 Improved Unit test to support  changes
This feature is linked to [Log when CheckoutTheme values are changed](https://github.com/checkout/frames-android/pull/88). Additionally, this PR is opened for adding theme object to align event property to Logging specification.
=> PIMOB-1094: Shifted evenTheme properties to theme object.

frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt, frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt, frames/src/test/java/com/checkout/frames/manager/PaymentFormStateManagerTest.kt, frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt
[PIMOB-1485: Pay button is still enabled after you exit the screen and return to it again](https://checkout.atlassian.net/browse/PIMOB-1485)
Payment state reset was added.
=> PIMOB-1485: Pay button is still enabled after you exit the screen and return to it again

checkout/src/main/java/com/checkout/CheckoutApiServiceFactory.kt, checkout/src/main/java/com/checkout/base/usecase/UseCase.kt
[PIMOB-1504: Allow Checkout Android to be accessed publicly for headless merchants](https://checkout.atlassian.net/browse/PIMOB-1504)
CheckoutApiServiceFactory is public and headless SDK can be used separately from UI-related functionality.
=> PIMOB-1504: Allow Checkout Android to be accessed publicly for headless merchants

frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonViewModel.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingAddress.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt, frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt, frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt, frames/src/test/java/com/checkout/frames/manager/PaymentFormStateManagerTest.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/models/BillingAddressTest.kt, frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt
[PIMOB-1767](https://checkout.atlassian.net/browse/PIMOB-1767)
**Problem**
Currently the `BillingAddress` is including the payment tokenisation process no matter whether the form is enabled or whether the `BillingAddress` is edited by the user. Which causes the SDK sending a default empty `BillingAddress` with the default country instead of a `null` value.
**Solution**
* Add a new field `PaymentStateManager#isBillingAddressEnabled: MutableStateFlow<Boolean>` to store a boolean of payment form is enabled.
* Add a new method `BillingAddress#isEdited()` to compare the current data is same as a default one.
* Use the field and method mentioned above in `PayButtonViewModel#provideCardData` to decide whether we need to provide the `BillingAddress` data. We should provide it only when the …
=> [Frame] disable sending billingAddress if form is disabled or not edited

frames/src/main/java/com/checkout/frames/component/country/CountryComponent.kt, frames/src/main/java/com/checkout/frames/component/country/CountryViewModel.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsScreen.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingAddress.kt, frames/src/main/java/com/checkout/frames/screen/countrypicker/CountryPickerViewModel.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt, frames/src/main/res/values-ar/strings.xml, frames/src/main/res/values-de/strings.xml, frames/src/main/res/values-es/strings.xml, frames/src/main/res/values-fr/strings.xml, frames/src/main/res/values-it/strings.xml, frames/src/main/res/values-nl/strings.xml, frames/src/main/res/values-ro/strings.xml, frames/src/main/res/values/strings.xml, frames/src/test/java/com/checkout/frames/component/country/CountryViewModelTest.kt, frames/src/test/java/com/checkout/frames/countrypicker/CountryPickerViewModelTest.kt, frames/src/test/java/com/checkout/frames/manager/PaymentFormStateManagerTest.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/models/BillingAddressTest.kt
[PIMOB-1767](https://checkout.atlassian.net/browse/PIMOB-1767) **AC2**
* `BillingAddressDetailsScreen` is default to make the country valid without checking what country is selected. ie, when the country is `INVALID_COUNTRY`, the `Done` button will be enabled if the other required fields are filled. 
* `BillingAddress` default the country by calling `Locale.getdefault().country` which might produce a empty string and thus get the `INVALID_COUNTRY`
* Default the country in `BillingAddress` constructor to `INVALID_COUNTRY`.
* Make the country `BillingAddressInputComponentState` to be invalid if the country is `INVALID_COUNTRY`.
* Add a new flag `visitedCountryPicker: MutableStateFlow<Boolean>` in `PaymentStateManager` to track whether the user has visited the `CountryPickerScreen`. If so …
=> [Frame] Default country to empty and add ability to show error message 

buildSrc/src/main/java/Dependencies.kt, buildSrc/src/main/java/Versions.kt, buildSrc/src/main/java/com/checkout/buildsrc/AndroidJunit4Config.kt, frames/src/main/java/com/checkout/frames/component/expirydate/ExpiryDateVisualTransformation.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingAddress.kt, frames/src/test/java/com/checkout/frames/component/expirydate/ExpiryDateVisualTransformationTest.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/models/BillingAddressTest.kt
[PIMOB-2040](https://checkout.atlassian.net/browse/PIMOB-2040)
ExpiryDateVisualTransformation returned an incorrect mapping between transformed and original offsets resulting in a crash. So, added robust logic to resolve it
[PIMOB-2040]: https://checkout.atlassian.net/browse/PIMOB-2040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> PIMOB-2040: Fixed expiry date crash

example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomBillingFormStyle.kt, example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentDetailsStyle.kt, example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentFormTheme.kt, frames/src/main/java/com/checkout/frames/component/cardholdername/CardHolderNameViewModel.kt, frames/src/main/java/com/checkout/frames/component/paybutton/PayButtonViewModel.kt, frames/src/main/java/com/checkout/frames/mapper/theme/BillingFormStyleMapper.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingAddress.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/models/BillingFormFields.kt, frames/src/main/java/com/checkout/frames/style/screen/default/DefaultBillingAddressDetailsStyle.kt, frames/src/main/java/com/checkout/frames/style/theme/DefaultPaymentFormTheme.kt, frames/src/main/java/com/checkout/frames/style/theme/PaymentFormComponentField.kt, frames/src/main/java/com/checkout/frames/utils/extensions/BillingAddressDetailsExtensions.kt, frames/src/main/java/com/checkout/frames/utils/extensions/BillingAddressExtensions.kt, frames/src/test/java/com/checkout/frames/component/cardholdername/CardHolderNameViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt, frames/src/test/java/com/checkout/frames/mock/BillingAddressDetailsTestData.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/usecase/BillingAddressInputComponentStateUseCaseTest.kt
[/PIMOB-2085](https://checkout.atlassian.net/browse/PIMOB-2085)
1 Add the cardholder name to the Billing form and the Default UI should not contain it
2. Merchants can set the field as an optional or mandatory 
3. Add support for it in theming capabilities
4. If the CardHolder name is added in the billing form and payment form then take this field from the payment form and ignore it from the billing form because token API has only 1 field for the cardholder name
5. Removed regex validation from cardholder name because API does not contain specific validation, unlike all address fields. See [reference](https://api-reference.checkout.com/#operation/getEntityBalances:~:text=any%20sensitive%20information.-,Request%20a%20token,-Exchange%20card%20details)
5. Changes in the sample app: Add the …
=> PIMOB-2085: Add cardholderField into a Billing form and hit the token api

example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt, example_app_frames/src/main/java/com/checkout/example/frames/ui/utils/PrefillDataHelper.kt, frames/src/androidTest/kotlin/com/checkout/frames/screen/paymentform/PaymentFormScreenTest.kt, frames/src/main/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModel.kt, frames/src/main/java/com/checkout/frames/di/module/PaymentModule.kt, frames/src/main/java/com/checkout/frames/mapper/BillingFormAddressToBillingAddressMapper.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt, frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt, frames/src/main/java/com/checkout/frames/screen/paymentform/PaymentFormViewModel.kt, frames/src/main/java/com/checkout/frames/utils/extensions/BillingAddressExtensions.kt, frames/src/test/java/com/checkout/frames/component/addresssummary/AddressSummaryViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/cardholdername/CardHolderNameViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/cardnumber/CardNumberViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/cardscheme/CardSchemeViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/country/CountryViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/cvv/CvvViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/expirydate/ExpiryDateViewModelTest.kt, frames/src/test/java/com/checkout/frames/component/paybutton/PayButtonViewModelTest.kt, frames/src/test/java/com/checkout/frames/countrypicker/CountryPickerViewModelTest.kt, frames/src/test/java/com/checkout/frames/manager/PaymentFormStateManagerTest.kt, frames/src/test/java/com/checkout/frames/mapper/BillingFormAddressToBillingAddressMapperTest.kt, frames/src/test/java/com/checkout/frames/mock/PaymentFormConfigTestData.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt, frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt, frames/src/test/java/com/checkout/frames/utils/extensions/BillingAddressExtensionsTest.kt
[PIMOB-2093](https://checkout.atlassian.net/browse/PIMOB-2093)
1. added capabilities of billing form address in prefilldata from payment form config
2. Added unit tests for it
_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._ 
1. Add billing form address in prefill data from payment form config. Refer main activity from sample app
2. verify address summary should update. (attached video)
3. Click on edit address summary and change the fields from the billing form, then Address summary should updated accordingly
[billling_recording_20230821_094805.webm](https://github.com/checkout/frames-android/assets/114917119/940681fe-0222-4933-83df-fd22c8b31453)
_Put an `x` in the boxes that …
=> PIMOB-2093: Injected prefilled billing-form address in paymentformconfig

checkout/src/main/java/com/checkout/base/model/Country.kt, checkout/src/main/java/com/checkout/tokenization/mapper/response/CardTokenizationNetworkDataMapper.kt, checkout/src/main/java/com/checkout/tokenization/mapper/response/PhoneEntityToPhoneDataMapper.kt, checkout/src/test/java/com/checkout/base/model/CountryTest.kt, checkout/src/test/java/com/checkout/tokenization/mapper/CardTokenizationNetworkDataMapperTest.kt, checkout/src/test/java/com/checkout/tokenization/mapper/response/PhoneEntityToPhoneDataMapperTest.kt
[PIMOB-2113](https://checkout.atlassian.net/browse/PIMOB-2113)
1 Receiving on token response, the country object from the phone should be correct as sent in the token request.
2 updated unit tests
Steps to reproduce the issue:
1 fill payment form along with billing address details. Choose a country as the united kingdom
2 Hit the pay button and verify the token response. It contains an invalid country object from the phone in the Token response from the SDK. See attached video for reference. 
Expected:
Receiving on token response, country object from the phone should be correct as sent in the token request.
[Uploading billling_recording_20230821_094805.webm…]()
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
=> PIMOB: 2133 -mapping of country in phone object from token response improved

frames/src/main/java/com/checkout/frames/component/country/CountryViewModel.kt, frames/src/main/java/com/checkout/frames/screen/billingaddress/billingaddressdetails/BillingAddressDetailsViewModel.kt, frames/src/main/java/com/checkout/frames/screen/countrypicker/CountryPickerViewModel.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentFormStateManager.kt, frames/src/main/java/com/checkout/frames/screen/manager/PaymentStateManager.kt, frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsScreen.kt, frames/src/main/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModel.kt, frames/src/test/java/com/checkout/frames/component/country/CountryViewModelTest.kt, frames/src/test/java/com/checkout/frames/countrypicker/CountryPickerViewModelTest.kt, frames/src/test/java/com/checkout/frames/manager/PaymentFormStateManagerTest.kt, frames/src/test/java/com/checkout/frames/screen/billingaddressdetails/BillingAddressDetailsViewModelTest.kt, frames/src/test/java/com/checkout/frames/screen/paymentdetails/PaymentDetailsViewModelTest.kt
[PIMOB-2119](https://checkout.atlassian.net/browse/PIMOB-2119)
Problem statement: When the merchant has not added any prefilled data navigates to the billing form and selects the country. Observed that country is updated in the payment form without saving it from the billing form.
Conflict is happening because the country is directly updating in  billing address from the payment state manager
Solution: Added new parameter `selectedCountry` in paymentstatemanager  
Case 1 (same for prefilled data)
1. open the billing form and select any country
2. Go back to the payment form, the country should not be updated there
Case-2:
1. Open the billing form, select any country and save the billing form (For instance, U.K)
2. Go back to the payment form, the country should  be updated there
3. Open …
=> PIMOB:2119 - Country prefilled without saving from billing form was fixed

frames/src/androidTest/kotlin/com/checkout/frames/cvvinputfield/CVVInputFieldTest.kt, frames/src/androidTest/kotlin/com/checkout/frames/cvvinputfield/InternalCVVComponentMediatorTest.kt, frames/src/androidTest/kotlin/com/checkout/frames/screen/PaymentFormScreenTest.kt, frames/src/main/java/com/checkout/frames/cvvinputfield/CVVInputField.kt, frames/src/main/java/com/checkout/frames/cvvinputfield/api/CVVComponentMediator.kt, frames/src/main/java/com/checkout/frames/cvvinputfield/api/InternalCVVComponentMediator.kt, frames/src/main/java/com/checkout/frames/cvvinputfield/viewmodel/CVVInputFieldViewModel.kt, frames/src/test/java/com/checkout/frames/cvvinputfield/viewmodel/CVVInputFieldViewModelTest.kt
[PIMOB-2181](https://checkout.atlassian.net/browse/PIMOB-2181)
1. Support to load only one CVV component from the same mediator
2. Support to load multiple CVV components from the different mediator
3. Enabled check for empty CVV length for all card schemes. For instance, if the merchant injects the Maestro, on 0 length CVV validation returns false for isCVVValid
4. Covered UI tests
Note: Sample app only load component and full design will be cover in following PRs
1. To validate load only one CVV component from the same mediator, call `mediator.CVVComponent()` in CVVTokenizationScreen multipletimes. Expected should be one cvv component in the screen
2. To validate load load multiple CVV components from the different mediator, create new mediators in CVVTokenizationScreen and expected …
=> PIMOB:2181 - CVV multiple loading support added

checkout/src/main/java/com/checkout/tokenization/logging/TokenizationEventLogger.kt, checkout/src/main/java/com/checkout/tokenization/logging/TokenizationLogger.kt, checkout/src/main/java/com/checkout/tokenization/repository/TokenRepositoryImpl.kt, checkout/src/test/java/com/checkout/tokenization/logging/TokenizationEventLoggerTest.kt, checkout/src/test/java/com/checkout/tokenization/repository/TokenRepositoryImplTest.kt, example_app_frames/src/main/java/com/checkout/example/frames/styling/CustomCVVInputFieldStyle.kt, frames/src/test/java/com/checkout/frames/mapper/BillingFormAddressToBillingAddressMapperTest.kt
[PIMOB-2168](https://checkout.atlassian.net/browse/PIMOB-2168)
Logged below data
1. Token request  
2. Token response (Success and failure)
Check logs"
1 Failure server error response [logs](https://app.datadoghq.com/logs?query=%40ApplicationName%3Acloudevents%20%40platform%3AAndroid%20%40productVersion%3A4.1.0%20%40appPackageName%3Acom.checkout.example.frames%20&agg_q=%40cloudevent.type&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice&event=AgAAAYsaX1aQKbyifgAAAAAAAAAYAAAAAEFZc2FYNmpIQUFEdUpxMFFFeWtsQndFQgAAACQAAAAAMDE4YjFhNjgtN2VkNS00OTRjLTgwOTUtMDY1NmViZThlMjgw&index=&messageDisplay=inline&panel=%7B%22queryString%22%3A%22%40cloudevent.type%3Acom.checkout.checkout-android.token_response%22%2C%22filters%22%3A%5B%7B%22isClicked%22%3Atrue%2C%22source%2 …
=> PIMOB:2168 - Tokenization Logging was implemented for CVV

example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/CVVTokenizationScreen.kt, frames/src/main/java/com/checkout/frames/mapper/InputFieldStyleToViewStyleMapper.kt
[PIMOB-2196](https://checkout.atlassian.net/browse/PIMOB-2196)
Support added in mapper for borderstorke in inputfield
Add borderstorke in containerstyle and see the change as below in screenshot
_If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered, etc..._
[PIMOB-2196]: https://checkout.atlassian.net/browse/PIMOB-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIMOB: 2196: Borderstroke issue fixed

README.md
[PIMOB-2356](https://checkout.atlassian.net/browse/PIMOB-2356)
Added details how to disable the cardholdername and billing form in payment form. Not included the part of disabling the fields in billing form because in details guide with code is available via [public doc ](https://www.checkout.com/docs/developer-resources/sdks/frames-android-sdk/customize-the-frames-android-sdk#Custom_BillingFormStyle)
[Preview link](https://github.com/checkout/frames-android/blob/c3fdc593e6b76e43f9df46fe96ce52b961ac6c98/README.md)
N/A
_If this is a …
=> PIMOB:2356 - add guide for disable the cardholder and billing form in readme

buildSrc/src/main/java/Dependencies.kt, buildSrc/src/main/java/Versions.kt, buildSrc/src/main/java/com/checkout/buildsrc/BaseDependencies.kt, buildSrc/src/main/java/com/checkout/buildsrc/CommonConfig.kt, checkout/build.gradle.kts, checkout/src/main/java/com/checkout/CheckoutApiServiceFactory.kt, checkout/src/main/java/com/checkout/logging/EventLogger.kt, checkout/src/main/java/com/checkout/tokenization/repository/TokenRepositoryImpl.kt, checkout/src/main/java/com/checkout/tokenization/usecase/RiskInstanceProvider.kt, checkout/src/main/java/com/checkout/tokenization/usecase/RiskSdkUseCase.kt, checkout/src/test/java/com/checkout/logging/EventLoggerTest.kt, checkout/src/test/java/com/checkout/tokenization/RiskSdkUseCaseTest.kt, checkout/src/test/java/com/checkout/tokenization/TokenNetworkApiClientTest.kt, checkout/src/test/java/com/checkout/tokenization/repository/TokenRepositoryImplTest.kt, settings.gradle.kts
https://checkout.atlassian.net/browse/PRISM-10044
Add Risk package to Frames
_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._ 
> For instance:
> 1. Go to the main screen
> 2. Tap on primary button
> 3. Verify the image is shown on the screen
=> PRISM-10044 - Add Risk package

README.md
[Release-28318](https://checkout.atlassian.net/browse/RELEASE-28318)
Including `maven { url 'https://maven.fpregistry.io/releases' }` in the readme to access dependency for Risk SDK.
=> [RELEASE-28318] Release 4.2.2 - update readme

.github/workflows/ui-test.yml, .github/workflows/verify-frames.yml, buildSrc/src/main/java/Versions.kt, checkout/src/main/java/com/checkout/CheckoutApiServiceFactory.kt, checkout/src/main/java/com/checkout/tokenization/repository/TokenRepositoryImpl.kt, checkout/src/main/java/com/checkout/tokenization/usecase/RiskInstanceProvider.kt, checkout/src/main/java/com/checkout/tokenization/usecase/RiskSdkUseCase.kt, checkout/src/test/java/com/checkout/tokenization/RiskSdkUseCaseTest.kt, checkout/src/test/java/com/checkout/tokenization/repository/TokenRepositoryImplTest.kt
https://checkout.atlassian.net/browse/PRISM-11245
Await acitons on the Risk SDK before continuing.
No changes in interaction or operation or test order.
NB: Regardless of success or failure within Risk, the completion handler is called on both scenarios.
NB: All asynchronous actions have a maximum timeout of 5 seconds.
=> Fix: Await risk sdk actions

buildSrc/src/main/java/Versions.kt, example_app_frames/lint-baseline.xml, frames/lint-baseline.xml
PIMOB-3506
Update Risk SDK version to `2.1.0`
No functionality change, it's required to support the latest fingerprint pro version
=> PIMOB-3506: Update Risk SDK version to 2.1.0
